# Project Properties
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true

# Mod Properties
mod_version=2.0.0
maven_group=nel.riposte
archives_base_name=riposte

# Core Environment Versions
minecraft_version=1.20.4
yarn_mappings=1.20.4+build.3
loader_version=0.19.3
fabric_api_version=0.97.3+1.20.4
loom_version=1.17-SNAPSHOT

# Exact Dependency Versions
fzzy_config_version=0.5.9+1.20.4
trinkets_version=3.8.1

# Visuals & UI Dependencies
modmenu_version=9.2.0
player_animator_version=1.0.2-rc1+1.20.4