# Project Properties
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true

# Mod Properties
mod_version=2.0.0-1.21v-fabric
maven_group=nel.riposte
archives_base_name=riposte

# Core Environment Versions
minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.16.2
fabric_api_version=0.102.0+1.21
loom_version=1.7-SNAPSHOT

# Exact Dependency Versions
fzzy_config_version=0.7.6+1.21
trinkets_version=3.10.0

# Visuals & UI Dependencies
modmenu_version=11.0.4
player_animator_version=2.0.4+1.21.1

# Better Combat & Dependencies
better_combat_version=2.4.0+1.21.1-fabric
cloth_config_version=15.0.130

# First-person Model
first_person_model_version=2.4.0+1.21.1-fabric

# ETF & EMF for Fresh Animations
etf_version=7.2.1-fabric-1.21
emf_version=3.3.5-fabric-1.21