# Project Properties
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true

# Mod Properties
mod_version=1.0.0
maven_group=nel.riposte
archives_base_name=riposte

# Core Environment Versions
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.11
fabric_api_version=0.92.0+1.20.1
loom_version=1.16-SNAPSHOT

# Exact Dependency Versions
fzzy_config_version=0.7.6+1.20.1
accessories_version=1.0.0-beta.47+1.20.1

# Visuals & UI Dependencies
modmenu_version=7.2.2
player_animator_version=1.0.2-rc1+1.20